spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #password: root
    url: jdbc:mysql://localhost:3306/car_manage?serverTimezone=GMT%2B8&characterEncoding=utf-8
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /static/**
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitmq
    password: rabbitmq
server:
  port: 8089

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml


# rabbitmq服务配置